### ISSUE TITLE
missing logic for largest uniq netblock use

### ISSUE THREAD

**Issue by bldur** [jrlevine/grepcidr3#1]
Hi!

Have been puzzling with a script to work as a simple nft ipset blocklist script.

Need to compare all CIDR ranges to itself and find the largest valid netblock.

Lacking a "match identical or larger size netblock than search term".

Allowing simple pipeing and looping operations to get largest uniq netblocks with sorting by removing duplicates.
Could be this works, but from documentation a bit quirky to work out how between cross reference example, -C and -D options.

May of course work to just blow up all the netblocks and re-create them, but involve half a million ip's.

Entirely possible i would assume, to include optimal performance for the tasks prips is used for.

NFT or Nftables complains and fails if there are collisions in adding a list of addresses or netblocks to ip set.

**Comment by jrlevine** [comment]
It doesn't do that, but the source is all here so feel free to make a version that does.
