### ISSUE TITLE
Algorithm to sanitize file with addreses and remove nestet overlapping blocks

### ISSUE THREAD

**Issue by bldur** [jrlevine/grepcidr3#2]
Can I leave this issue, for myself and someone else with time and desire to write or improve?

what i do now in shell, and would be nice feature in grepcidr.

Perfectly fine speed wise with more than 2000 lines and addres block that matches 5 as top hit, not sure if its misses or catches all, but should..

And well, i use prips to print out blocks /25 and smaller, which could be an option as it would be more lines with square scaling without.

```
sanitize_cidr() {

file="$1"
overlaps=$(cat $file | while read line ; do
                        echo "$(grepcidr -D $line $file | wc -l) $line\n"
                done | sort -r)
N=$(echo -e $overlaps | awk 'NR==1{print $1}')


# start with lowest N cidr with overlaps to highest in case they are nested.
for i in $(seq 2 $N) ; do
        echo -e $overlaps | grep "$i\s" | awk '{print$2}' | while read line ;do
                cidr_remove=$(grepcidr -D $line $file | sort -t "/" -k2 | tail -n+2 | sed -e 's/[]\/$*.^[]/\\&/g')
                for i in $cidr_remove ;do
                        sed -i "/$i/d" $file
                done
        done

done

}
```

**Comment by 69Suka69** [comment]
- Лизать```

```

**Comment by 69Suka69** [comment]
> - Лизать```
> 
> ```

**Comment by jrlevine** [comment]
If you want to combine overlaping IP ranges, it's easy to do in a tiny script using the standard python ipaddress library, and probably other language libraries too. There's no need to add a wart to this program.

**Comment by bldur** [comment]
This algorithm, as such, checkes for collisions between ranges and sets.
I do not think I can get it to run faster in shell.

As such, this wart belongs in cidrgrep.

Do something simple right, and as such, involving this is completion breaking naming is THE wart.

**Comment by jrlevine** [comment]
Like I said, this would be easy to do in a python script using the standard python ipaddress module. I am not going to add it to grepcidr.
If you don't have sufficient python skills and this is important to you, I'm sure you can find someone who'll program it for you, probably not for free.

**Comment by bldur** [comment]
This makes it clear that we are worlds apart, and i recommend crappy shell script ontop of small C programs over the pleasure of python, ontop of numpy, ontop of FFTW and hand optimized blas and lapack libraries to make processing of networking data ontop of network equipment or embedded computers.

**Comment by bldur** [comment]
In accord with UNIX philosophy and best practices, if it looks like an algorithm that benefit from compilers optimizations, and can be implemented with efficient and machine readable code, possibly with memory management, arrays and pointer arithmetic, it probably should be. I get that you feel it doesn't belong in grepcidr, but since this involve the grep algorithm and CIDR operations, it kind of seem like a reasonable fit.

I have no qualms with your stance, and should I find the time and interest for such a project I may very well without having any professional needs or benefit of a open source portefolio as such. This is a piece of shit shell script, but it is reasonable fast and doesn't come with a pile of framework dependencies and satisfied with it being either a closed or open issue.

**Comment by thezoggy** [comment]
@bldur you might be interested in checking out: https://github.com/job/aggregate6
